-- pg16_discount_consolidated.sql
-- Postgres 16 init script for docker-entrypoint-initdb.d
-- Creates role + database + schema + tables + seed data for "discount" app.

-- ============================================================================
-- 0) Create role/user dis_adm if it does not exist
--    NOTE: We set a password for Spring Boot to use.
-- ============================================================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_catalog.pg_roles
    WHERE rolname = 'dis_adm'
  ) THEN
    CREATE ROLE dis_adm
      WITH LOGIN
      PASSWORD 'dis_adm_2026'
      SUPERUSER;
  ELSE
    -- ensure password is as expected (optional)
    ALTER ROLE dis_adm WITH PASSWORD 'dis_adm_2026';
  END IF;
END
$$;

-- ============================================================================
-- 1) Create database discount if it does not exist (CREATE DATABASE cannot be in DO)
-- ============================================================================
SELECT 'CREATE DATABASE discount WITH TEMPLATE = template0 ENCODING = ''UTF8'''
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'discount')
\gexec

-- Ensure DB owner + privileges (safe if already created)
ALTER DATABASE discount OWNER TO dis_adm;
GRANT ALL ON DATABASE discount TO dis_adm;

-- ============================================================================
-- 2) Switch into discount DB for the rest
-- ============================================================================
\connect discount

-- ============================================================================
-- 3) Create schema discount (owned by dis_adm), grants, defaults
-- ============================================================================
CREATE SCHEMA IF NOT EXISTS discount AUTHORIZATION dis_adm;
ALTER SCHEMA discount OWNER TO dis_adm;

GRANT ALL ON SCHEMA discount TO dis_adm;

-- Default privileges: objects created by dis_adm in schema discount -> dis_adm has all
ALTER DEFAULT PRIVILEGES FOR ROLE dis_adm IN SCHEMA discount
  GRANT ALL ON TABLES TO dis_adm;

ALTER DEFAULT PRIVILEGES FOR ROLE dis_adm IN SCHEMA discount
  GRANT ALL ON SEQUENCES TO dis_adm;

ALTER DEFAULT PRIVILEGES FOR ROLE dis_adm IN SCHEMA discount
  GRANT EXECUTE ON FUNCTIONS TO dis_adm;

ALTER DEFAULT PRIVILEGES FOR ROLE dis_adm IN SCHEMA discount
  GRANT USAGE ON TYPES TO dis_adm;

-- Ensure subsequent DDL uses this schema
SET search_path TO discount;

-- ============================================================================
-- 4) DDL - Tables
-- ============================================================================

-- customers
CREATE TABLE IF NOT EXISTS discount.customers (
    cus_id bigint NOT NULL,
    cus_full_name character varying NOT NULL,
    cus_type character varying NOT NULL,
    cus_registration_date date NOT NULL,
    cus_blacklisted boolean NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    CONSTRAINT cus_type_check CHECK (
      ((cus_type)::text = ANY ((ARRAY['EMPLOYEE'::character varying, 'LOYAL'::character varying, 'AFFILIATE'::character varying])::text[]))
    )
);

ALTER TABLE discount.customers OWNER TO dis_adm;

-- identity column + sequence (runs only once; guarded by checking column default)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema='discount' AND table_name='customers'
      AND column_name='cus_id'
      AND column_default LIKE 'generated by default as identity%'
  ) THEN
    ALTER TABLE discount.customers
      ALTER COLUMN cus_id
      ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME discount.customers_cus_id_seq
        START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
      );
  END IF;
END
$$;

ALTER TABLE discount.customers
  ADD CONSTRAINT customers_pkey PRIMARY KEY (cus_id);


-- items
CREATE TABLE IF NOT EXISTS discount.items (
    itm_id bigint NOT NULL,
    itm_name character varying(100) NOT NULL,
    itm_category character varying(20) NOT NULL,
    itm_price numeric(10,2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_category CHECK (
      ((itm_category)::text = ANY ((ARRAY['GROCERY'::character varying, 'NON_GROCERY'::character varying])::text[]))
    ),
    CONSTRAINT chk_price_positive CHECK ((itm_price > (0)::numeric))
);

ALTER TABLE discount.items OWNER TO dis_adm;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema='discount' AND table_name='items'
      AND column_name='itm_id'
      AND column_default LIKE 'generated by default as identity%'
  ) THEN
    ALTER TABLE discount.items
      ALTER COLUMN itm_id
      ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME discount.items_itm_id_seq
        START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
      );
  END IF;
END
$$;

ALTER TABLE discount.items
  ADD CONSTRAINT items_pkey PRIMARY KEY (itm_id);


-- bills
CREATE TABLE IF NOT EXISTS discount.bills (
    bll_id bigint NOT NULL,
    cus_id bigint NOT NULL,
    bll_gross_total numeric(12,2) NOT NULL,
    bll_grocery_total numeric(12,2) DEFAULT 0 NOT NULL,
    bll_non_grocery_total numeric(12,2) DEFAULT 0 NOT NULL,
    bll_percent_discount_type character varying(50),
    bll_percent_discount_amount numeric(12,2) DEFAULT 0 NOT NULL,
    bll_flat_discount_amount numeric(12,2) DEFAULT 0 NOT NULL,
    bll_total_discount numeric(12,2) DEFAULT 0 NOT NULL,
    bll_net_payable numeric(12,2) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_net_payable_positive CHECK ((bll_net_payable >= (0)::numeric)),
    CONSTRAINT chk_original_amount_positive CHECK ((bll_gross_total >= (0)::numeric))
);

ALTER TABLE discount.bills OWNER TO dis_adm;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema='discount' AND table_name='bills'
      AND column_name='bll_id'
      AND column_default LIKE 'generated by default as identity%'
  ) THEN
    ALTER TABLE discount.bills
      ALTER COLUMN bll_id
      ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME discount.bills_bll_id_seq
        START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
      );
  END IF;
END
$$;

ALTER TABLE discount.bills
  ADD CONSTRAINT bill_history_pkey PRIMARY KEY (bll_id);

-- Percent discount type check (your dump had NOT VALID; keep it consistent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'chk_bll_percent_discount_type'
  ) THEN
    ALTER TABLE discount.bills
      ADD CONSTRAINT chk_bll_percent_discount_type
      CHECK (
        ((bll_percent_discount_type)::text = ANY ((ARRAY['EMPLOYEE'::character varying, 'LOYAL'::character varying, 'AFFILIATE'::character varying])::text[]))
      ) NOT VALID;
  END IF;
END
$$;

-- FK bills -> customers
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_bill_customer'
  ) THEN
    ALTER TABLE ONLY discount.bills
      ADD CONSTRAINT fk_bill_customer
      FOREIGN KEY (cus_id)
      REFERENCES discount.customers(cus_id)
      ON DELETE RESTRICT;
  END IF;
END
$$;

-- Comments
COMMENT ON COLUMN discount.bills.bll_gross_total IS 'The gross total of all item prices';
COMMENT ON COLUMN discount.bills.bll_grocery_total IS 'The total of grocery category item prices';
COMMENT ON COLUMN discount.bills.bll_non_grocery_total IS 'The total of non grocery prices';
COMMENT ON COLUMN discount.bills.bll_percent_discount_amount IS 'The calculated percentage discount deduction';

-- ============================================================================
-- 5) Seed data
-- ============================================================================

-- customers
INSERT INTO discount.customers VALUES
(1, 'Ahmed Almutairi', 'EMPLOYEE', '2023-01-15', false, '2026-01-13 11:22:42.831374+03', '2026-01-13 11:22:42.831374+03')
ON CONFLICT DO NOTHING;

INSERT INTO discount.customers VALUES
(2, 'Sarah Johnson', 'LOYAL', '2022-11-03', false, '2026-01-13 11:22:42.831374+03', '2026-01-13 11:22:42.831374+03'),
(3, 'Mohammed Alshatti', 'AFFILIATE', '2024-02-20', false, '2026-01-13 11:22:42.831374+03', '2026-01-13 11:22:42.831374+03'),
(4, 'Fatima Alharbi', 'LOYAL', '2021-08-09', false, '2026-01-13 11:22:42.831374+03', '2026-01-13 11:22:42.831374+03'),
(5, 'David Smith', 'AFFILIATE', '2023-06-14', true,  '2026-01-13 11:22:42.831374+03', '2026-01-13 11:22:42.831374+03'),
(6, 'Aisha Alqahtani', 'EMPLOYEE', '2022-03-27', false, '2026-01-13 11:22:42.831374+03', '2026-01-13 11:22:42.831374+03'),
(7, 'Omar Alenezi', 'LOYAL', '2024-05-01', false, '2026-01-13 11:22:42.831374+03', '2026-01-13 11:22:42.831374+03'),
(8, 'Emily Brown', 'AFFILIATE', '2021-12-19', false, '2026-01-13 11:22:42.831374+03', '2026-01-13 11:22:42.831374+03'),
(9, 'Yousef Alotaibi', 'EMPLOYEE', '2023-09-07', true,  '2026-01-13 11:22:42.831374+03', '2026-01-13 11:22:42.831374+03'),
(10,'Linda Martinez', 'LOYAL', '2022-04-30', false, '2026-01-13 11:22:42.831374+03', '2026-01-13 11:22:42.831374+03')
ON CONFLICT DO NOTHING;

-- items
INSERT INTO discount.items VALUES
(1, 'Milk 1L', 'GROCERY', 1.25, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(2, 'Bread Loaf', 'GROCERY', 0.95, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(3, 'Eggs (12 pack)', 'GROCERY', 2.75, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(4, 'Rice 5kg', 'GROCERY', 6.50, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(5, 'Chicken Breast', 'GROCERY', 4.20, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(6, 'Apple Juice', 'GROCERY', 1.80, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(7, 'Cheese Block', 'GROCERY', 3.40, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(8, 'Olive Oil', 'GROCERY', 5.90, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(9, 'Pasta Pack', 'GROCERY', 1.10, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(10,'Sugar 2kg', 'GROCERY', 2.30, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(11,'Shampoo', 'NON_GROCERY', 3.75, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(12,'Toothpaste', 'NON_GROCERY', 2.10, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(13,'Laundry Detergent', 'NON_GROCERY', 7.40, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(14,'Dish Soap', 'NON_GROCERY', 1.90, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(15,'Paper Towels', 'NON_GROCERY', 2.60, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(16,'Trash Bags', 'NON_GROCERY', 3.30, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(17,'Light Bulbs (4)', 'NON_GROCERY', 4.80, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(18,'Batteries AA', 'NON_GROCERY', 5.20, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(19,'Notebook', 'NON_GROCERY', 1.50, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498'),
(20,'Pen Pack', 'NON_GROCERY', 1.20, '2026-01-14 00:39:42.918498', '2026-01-14 00:39:42.918498')
ON CONFLICT DO NOTHING;

-- bills
INSERT INTO discount.bills VALUES
(1, 1, 21.30, 9.00, 12.30, 'EMPLOYEE', 3.69, 0.00, 3.69, 17.61,
 '2026-01-14 00:43:21.571772+03', '2026-01-14 00:43:21.57277+03')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- 6) Sequence values (optional but keeps IDs aligned with seeded data)
-- ============================================================================
SELECT pg_catalog.setval('discount.items_itm_id_seq', 20, true);
SELECT pg_catalog.setval('discount.bills_bll_id_seq', 1, true);

-- In your dump it was (1,false) for customers; that would make next id = 1 (bad).
-- Since you inserted cus_id up to 10, set the sequence properly:
SELECT pg_catalog.setval('discount.customers_cus_id_seq', 10, true);

-- ============================================================================
-- Done
-- ============================================================================
